import { test, expect } from "@playwright/test";

test("zero-downtime rotation, final-secret safeguard, compromise and one-time visibility", async ({ page, request }) => {
  await page.goto("/apps");
  await page.locator("header").getByRole("button", { name: "Add app" }).click();
  await page.getByLabel("Name", { exact: true }).fill(`Secret Product ${Date.now()}`);
  await page.getByLabel("Client label").fill("Rotation worker");
  await page.getByLabel("Purpose", { exact: true }).selectOption("workload");
  const creation = page.waitForResponse(r => r.url().endsWith("/api/v1/apps") && r.request().method() === "POST");
  await page.getByRole("button", { name: "Create", exact: true }).click();
  const f = await (await creation).json();
  await expect(page).toHaveURL(/\/apps\/.+\/setup/);
  await expect(page.getByRole("dialog")).toContainText(f.clientSecret);
  await page.getByRole("button", { name: "Done", exact: true }).click();
  await expect(page.getByText(f.clientSecret, { exact: true })).toHaveCount(0);
  const worker = page.getByRole("row").filter({ hasText: "Rotation worker" });
  await worker.getByRole("button", { name: "Secrets", exact: true }).click();
  const dialog = page.getByRole("dialog");
  await expect(dialog).toContainText("Never used");
  await expect(dialog).toContainText("No expiry");
  const old = dialog.getByRole("row").filter({ hasText: f.secret.id });
  await old.getByRole("button", { name: "Revoke", exact: true }).click();
  await expect(dialog.getByRole("status")).toContainText("last usable secret");
  await expect(dialog.getByRole("button", { name: "Confirm revocation", exact: true })).toBeDisabled();
  await dialog.getByRole("button", { name: "Add replacement", exact: true }).click();
  await page.getByLabel("Secret label (optional)").fill("Deployment two");
  await page.getByLabel("Secret expiry (optional)").fill("2035-01-01T12:00");
  const created = page.waitForResponse(r => r.url().endsWith("/secrets") && r.request().method() === "POST");
  await dialog.getByRole("button", { name: "Create secret", exact: true }).click();
  const replacement = await (await created).json();
  await expect(page.getByTestId("client-secret-value")).toHaveText(replacement.clientSecret);
  expect(replacement.secret.label).toBe("Deployment two");
  expect(replacement.secret.expiresAt).toContain("2035-01-01");
  await dialog.getByRole("button", { name: "Done", exact: true }).click();
  await expect(page.getByTestId("client-secret-value")).toHaveCount(0);
  await expect(page.getByText(replacement.clientSecret, { exact: true })).toHaveCount(0);
  const resource = `urn:z0:e2e:secrets:${f.app.id}`;
  const permission = await page.evaluate(async ({ appId, clientId, audience }) => {
    const csrf = decodeURIComponent(document.cookie.match(/(?:^|; )z0_csrf=([^;]+)/)![1]!);
    const headers = { "Content-Type": "application/json", "X-CSRF-Token": csrf };
    const created = await fetch(`/api/v1/apps/${appId}/resources`, { method: "POST", headers, body: JSON.stringify({ name: "Worker API", audience, scopes: [] }) });
    if (!created.ok) return created.status;
    const res = await created.json();
    return (await fetch(`/api/v1/apps/${appId}/clients/${clientId}/resources/${res.id}`, { method: "PUT", headers, body: JSON.stringify({ scopes: [] }) })).status;
  }, { appId: f.app.id, clientId: f.client.id, audience: resource });
  expect(permission).toBe(200);
  async function authenticate(secret: string, basic = false) {
    const form: Record<string, string> = { grant_type: "client_credentials", resource };
    const headers: Record<string, string> = {};
    if (basic) headers.Authorization = `Basic ${Buffer.from(`${f.client.clientId}:${secret}`).toString("base64")}`;
    else { form.client_id = f.client.clientId; form.client_secret = secret; }
    return request.post("/oauth/token", { form, headers });
  }
  expect((await authenticate(f.clientSecret)).status()).toBe(200);
  expect((await authenticate(replacement.clientSecret, true)).status()).toBe(200);
  await dialog.getByRole("button", { name: "Close secrets", exact: true }).click();
  await page.reload();
  await worker.getByRole("button", { name: "Secrets", exact: true }).click();
  await expect(page.getByText(f.clientSecret, { exact: true })).toHaveCount(0);
  await expect(page.getByText(replacement.clientSecret, { exact: true })).toHaveCount(0);
  await expect(old).not.toContainText("Never used");
  await old.getByRole("button", { name: "Revoke", exact: true }).click();
  await dialog.getByRole("button", { name: "Confirm revocation", exact: true }).click();
  await expect(old).toContainText("revoked");
  expect((await authenticate(f.clientSecret)).status()).toBe(401);
  expect((await authenticate(replacement.clientSecret, true)).status()).toBe(200);
  const next = dialog.getByRole("row").filter({ hasText: replacement.secret.id });
  await next.getByRole("button", { name: "Revoke", exact: true }).click();
  await expect(dialog.getByRole("button", { name: "Confirm revocation", exact: true })).toBeDisabled();
  await dialog.getByRole("checkbox", { name: /Suspected compromise/ }).check();
  await dialog.getByRole("button", { name: "Revoke compromised secret", exact: true }).click();
  await expect(next).toContainText("compromised");
  expect((await authenticate(replacement.clientSecret)).status()).toBe(401);
  await dialog.getByRole("button", { name: "Close secrets", exact: true }).click();
  await page.reload();
  await worker.getByRole("button", { name: "Secrets", exact: true }).click();
  await expect(next).toContainText("revoked");
  await expect(next.getByRole("button", { name: "Revoke", exact: true })).toHaveCount(0);
});
