/**
 * Bootstrap Control Plane Endpoints
 * 
 * Manages one-time platform initialization and setup state detection.
 * These endpoints enable secure self-hosted deployment with zero pre-configuration.
 */

import { SQL } from 'bun';
import { hashSecret, generateRandomString, logger, PATTERNS } from '../lib';
import { createDatabaseClient } from '../../database/runtime';
import { resolveDatabaseUrl } from '../../database/migration-runner';

export interface BootstrapStatusResponse {
  bootstrapped: boolean;
  requires_setup: boolean;
  timestamp: string;
}

export interface BootstrapInitializeRequest {
  platform_name: string;
  admin_email: string;
  admin_password: string;
  confirm_password: string;
}

export interface BootstrapInitializeResponse {
  platform_id: string;
  bootstrap_token: string;
  admin_email: string;
  setup_complete: boolean;
  timestamp: string;
}

/**
 * GET /api/v1/bootstrap/status
 * 
 * Check if platform initialization is already complete.
 * Returns whether setup wizard should be shown.
 */
export async function handleBootstrapStatus(_req: Request): Promise<Response> {
  const db = createDatabaseClient(resolveDatabaseUrl());

  try {
    const rows = await (db as unknown as SQL).unsafe(`
      SELECT COUNT(*) as platform_count
      FROM platforms
      WHERE deleted_at IS NULL
    `);

    const platformCount = (rows as Array<{ platform_count: number }>)[0]?.platform_count ?? 0;

    const response: BootstrapStatusResponse = {
      bootstrapped: platformCount > 0,
      requires_setup: platformCount === 0,
      timestamp: new Date().toISOString(),
    };

    return Response.json(response, { status: 200 });
  } catch (error) {
    logger.error('Bootstrap status check failed', { error: String(error) });
    return Response.json(
      { error: 'Failed to check bootstrap status' },
      { status: 500 }
    );
  } finally {
    await db.close();
  }
}

/**
 * POST /api/v1/bootstrap/initialize
 * 
 * One-time endpoint to initialize platform, create admin user, and issue bootstrap token.
 * Can only succeed once - subsequent calls fail if platform already exists.
 */
export async function handleBootstrapInitialize(req: Request): Promise<Response> {
  if (req.method !== 'POST') {
    return Response.json(
      { error: 'Method not allowed' },
      { status: 405 }
    );
  }

  // Parse request body
  let payload: BootstrapInitializeRequest;
  try {
    payload = await req.json() as BootstrapInitializeRequest;
  } catch {
    return Response.json(
      { error: 'Invalid JSON request body' },
      { status: 400 }
    );
  }

  // Validate input
  const validationErrors: Record<string, string> = {};

  if (!payload.platform_name || typeof payload.platform_name !== 'string') {
    validationErrors.platform_name = 'Platform name is required';
  } else if (payload.platform_name.length < 3 || payload.platform_name.length > 255) {
    validationErrors.platform_name = 'Platform name must be 3-255 characters';
  }

  if (!payload.admin_email || typeof payload.admin_email !== 'string') {
    validationErrors.admin_email = 'Admin email is required';
  } else if (!PATTERNS.EMAIL.test(payload.admin_email)) {
    validationErrors.admin_email = 'Invalid email format';
  }

  if (!payload.admin_password || typeof payload.admin_password !== 'string') {
    validationErrors.admin_password = 'Password is required';
  } else if (payload.admin_password.length < 12) {
    validationErrors.admin_password = 'Password must be at least 12 characters';
  } else if (!PATTERNS.STRONG_PASSWORD.test(payload.admin_password)) {
    validationErrors.admin_password = 'Password must contain uppercase, lowercase, number, and special character';
  }

  if (payload.confirm_password !== payload.admin_password) {
    validationErrors.confirm_password = 'Passwords do not match';
  }

  if (Object.keys(validationErrors).length > 0) {
    return Response.json(
      { error: 'Validation failed', details: validationErrors },
      { status: 400 }
    );
  }

  const db = createDatabaseClient(resolveDatabaseUrl());

  try {
    // Start transaction
    const result = await (db as unknown as SQL).begin(async (tx) => {
      // Check if platform already exists
      const existingRows = await (tx as unknown as SQL).unsafe(`
        SELECT COUNT(*) as platform_count
        FROM platforms
        WHERE deleted_at IS NULL
      `);

      const platformCount = (existingRows as Array<{ platform_count: number }>)[0]?.platform_count ?? 0;
      if (platformCount > 0) {
        throw new Error('Platform already initialized');
      }

      // Create platform (UUID generated by PostgreSQL)
      const platformResult = await (tx as unknown as SQL).unsafe(`
        INSERT INTO platforms (name, display_name, created_at, updated_at)
        VALUES ($1, $2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
        RETURNING id
      `, [payload.platform_name, payload.platform_name]);

      const platformId = (platformResult as Array<{ id: string }>)[0]?.id;
      if (!platformId) {
        throw new Error('Failed to create platform');
      }

      // Create platform admin
      const passwordHash = await hashSecret(payload.admin_password);
      await (tx as unknown as SQL).unsafe(`
        INSERT INTO platform_admins (platform_id, email, password_hash, created_at, updated_at)
        VALUES ($1, $2, $3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
      `, [platformId, payload.admin_email, passwordHash]);

      // Create bootstrap token (valid for 24 hours)
      const bootstrapToken = generateRandomString(32);
      const tokenHash = await hashSecret(bootstrapToken);
      const expiresAt = new Date(Date.now() + 24 * 60 * 60 * 1000); // 24 hours

      await (tx as unknown as SQL).unsafe(`
        INSERT INTO bootstrap_tokens (platform_id, token_hash, created_at, expires_at)
        VALUES ($1, $2, CURRENT_TIMESTAMP, $3)
      `, [platformId, tokenHash, expiresAt.toISOString()]);

      return { platformId, bootstrapToken };
    });

    logger.info('Platform initialized successfully', {
      platformId: result.platformId,
      adminEmail: payload.admin_email,
    });

    const response: BootstrapInitializeResponse = {
      platform_id: result.platformId,
      bootstrap_token: result.bootstrapToken,
      admin_email: payload.admin_email,
      setup_complete: true,
      timestamp: new Date().toISOString(),
    };

    return Response.json(response, { status: 201 });
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);

    if (errorMessage === 'Platform already initialized') {
      return Response.json(
        { error: 'Platform already initialized' },
        { status: 409 }
      );
    }

    logger.error('Bootstrap initialization failed', { error: errorMessage });
    return Response.json(
      { error: 'Bootstrap initialization failed' },
      { status: 500 }
    );
  } finally {
    await db.close();
  }
}
